pages:
  image: python:trixie
  script:
  - python3 -m venv .
  - . ./bin/activate
  - pip install --upgrade -r requirements.txt --no-cache-dir
  - make html
  - mv build/html public
  artifacts:
    paths:
    - public
  only:
  - main
