pages:
  image: rockylinux:9
  script:
  - python3 -m venv .
  - . ./bin/activate
  - PIP_CACHE_DIR=/tmp/tah568/pip_cache pip install --upgrade -r requirements.txt
  - make html
  - mv build/html public
  artifacts:
    paths:
    - public
  only:
  - main
